# Generated by Django 4.0.4 on 2022-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostClass',
            fields=[
                ('Post_id', models.IntegerField()),
                ('Title_post_tr', models.CharField(max_length=50)),
                ('Title_post', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Crop_content', models.CharField(max_length=250)),
                ('Full_content', models.CharField(max_length=50)),
                ('Views_post', models.IntegerField()),
                ('Favorites', models.BooleanField()),
                ('Likes', models.SmallIntegerField(primary_key=1, serialize=False, verbose_name=-1)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
